import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'

export default function Home() {
  const [episodes, setEpisodes] = useState([])

  useEffect(() => {
    async function fetchMediaData() {
      const response = await fetch('http://localhost:3000/api/data')
      const media = await response.json()
      setEpisodes(media)
    }

    fetchMediaData()
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className="card w-96 bg-base-100 shadow-xl glass">
          <figure>
            <img src="/images/stock/photo-1606107557195-0e29a4b5b4aa.jpg" alt="Shoes" />
          </figure>
          <div className="card-body">
            <h2 className="card-title">Shoes!</h2>
            <p>If a dog chews shoes whose shoes does he choose?</p>
            <div className="card-actions justify-end">
              <button className="btn btn-primary">Buy Now</button>
            </div>
          </div>
        </div>
        {/* {episodes.map((episode, index) => (
          <div key={index}>
            <h2>{episode.episode}</h2>
            <p>{episode.link}</p>
            <p>{episode.guid}</p>
            <p>{episode.pubDate}</p>
            <ul>
              {Object.entries(episode.mediaList).map(([category, items]) => (
                <li key={category}>
                  <strong>{category}</strong>
                  <ul>
                    {Array.isArray(items)
                      ? items.map((item, i) => <li key={i}>{JSON.stringify(item)}</li>)
                      : null}
                  </ul>
                </li>
              ))}
            </ul>
          </div>
        ))} */}
      </div>
    </>
  )
}
